### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by LazyTarget** [jobbrIO/jobbr-dashboard#3]
I would like to install the Jobbr.Dashboard on a .NET Core project, however this is currently not possible

I get these error messages when trying to install the NuGet package "**Jobbr.Dashboard**" with the version **v.1.2.0**

![VS errors](https://user-images.githubusercontent.com/959409/64016052-40ed4c80-cb26-11e9-9583-904a080a6845.png)

**Comment by olibanjoli** [comment]
Jobbr is currently not compatible with .NET Core. It's on our roadmap but currently we're not working on .NET Core support.

**Comment by eXpl0it3r** [comment]
Implemented with #36
